import type { GalleryMediaItem } from '@/types';

const ESCOLA_DOS_NOSSOS_AVOS_PHOTOS = [
  '/internal-pages/escola-dos-nossos-avos/foto-01-dsc-0113.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-02-dsc-0123.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-03-dsc-0133.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-04-dsc-0134.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-05-dsc-0136.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-06-dsc-0154.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-07-dsc-0260.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-08-dsc-0261.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-09-dsc-0262.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-10-dsc-0263.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-11-dsc-0264.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-12-dsc-0265.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-13-dsc-0266.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-14-dsc-0267.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-15-dsc-0268.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-16-dsc-0269.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-17-dsc-0270.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-18-dsc-0271.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-19-dsc-0272.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-20-dsc-0273.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-21-dsc-0274.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-22-dsc-0275.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-23-dsc-0276.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-24-dsc-0277.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-25-dsc-0278.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-26-dsc-0279.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-27-dsc-0280.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-28-dsc-0281.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-29-dsc-0282.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-30-dsc-0283.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-31-dsc-0284.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-32-dsc-0285.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-33-dsc-0286.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-34-dsc-0287.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-35-dsc-0288.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-36-dsc-0289.jpg',
  '/internal-pages/escola-dos-nossos-avos/foto-37-escola-dos-nossos-avos.jpg',
];

export const escolaDosNossosAvosFallbackGallery: GalleryMediaItem[] = ESCOLA_DOS_NOSSOS_AVOS_PHOTOS.map(
  (source, index) => ({
    id: `escola-dos-nossos-avos-fallback-${index + 1}`,
    title: `Escola dos Nossos Avós ${index + 1}`,
    description: 'Arquivo fotográfico da Escola dos Nossos Avós',
    type: 'photo',
    context: 'escola-dos-nossos-avos',
    source,
    thumbnail: source,
    mimeType: 'image/jpeg',
    published: true,
    createdAt: '2026-07-02T00:00:00.000Z',
    updatedAt: '2026-07-02T00:00:00.000Z',
  })
);
